# Generated by Django 5.1.5 on 2025-01-20 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_categorie_article_categorie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date_publication',
            field=models.DateField(auto_now_add=True),
        ),
    ]
